# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='numgym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Gymcana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymcana',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prova',
            name='nom',
            field=models.CharField(max_length=20),
        ),
    ]
