# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160220_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='superada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
