# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prova_superada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='provacodi',
            name='codi',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provatest',
            name='respostacorrecta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='idpregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProvaTest'),
        ),
    ]
