# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160220_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resposta',
            new_name='RespostaTest',
        ),
    ]
